name: billing_software
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter_riverpod: ^2.5.1
  pdf: ^3.11.3
  printing: ^5.14.2
  supabase_flutter: ^2.5.0
  path_provider: ^2.1.2
  go_router: ^13.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
